future: true

# core settings
title: David Young
email: me@davidyoung.tech
email_address: me@davidyoung.tech

# bio's
description: > # this means to ignore newlines until "baseurl:"
  David Young is a Web Developer based in Brisbane, Australia 
  with a keen interest in Website Development and Design trying to make the web faster.
short_description: "David Young is a Web Developer based in Brisbane, Australia with a keen interest in Website Development and Design."
base_keywords: "web, developer, blog, web developer, brisbane, australia, david, young, david young"

# URLs
baseurl: "" # subpath, eg /blog
url: "https://davidyoung.tech" # base url
theme_colour: "#F4F2F0"

# usernames
twitter_username: dayvidwhy
github_username:  dayvidwhy

# Build settings
markdown: kramdown
sass:
  style: compressed

exclude:
    - sw.js